language: node_js
node_js:
  - "10"

services:
  - docker

before_install:
  - docker build --tag travis .
  - docker build -f Dockerfile-acceptance -t travis-acceptance .

  - docker run -d --name=redis redis
  - docker run -d -e CASEWORKER_EMAIL=test@example.com -e NODE_ENV=ci -e DISABLE_CSP=true --net=container:redis --name=travis travis
  - docker run --rm -e CASEWORKER_EMAIL=test@example.com --net=container:travis travis-acceptance
  - docker rm -vf travis redis

script: echo "Tests Successful!"

notifications:
  email: false
